# Generacy Development Cluster Setup
#
# Run this script after cloning/forking to configure the cluster
# for your project. Idempotent — safe to re-run at any time.
#
# If .generacy/config.yaml already exists (from the onboarding UI,
# manual creation, or a previous run), the script reads project info
# from it and skips those prompts.
#
# Usage:
#   .generacy\setup.ps1
#   .generacy\setup.ps1 -RepoUrl https://github.com/your-org/your-repo.git

param(
    [string]$RepoUrl = ""
)

$ErrorActionPreference = "Stop"
$ProjectDir = Split-Path $PSScriptRoot -Parent
$DevcontainerDir = Join-Path (Join-Path $ProjectDir ".devcontainer") "generacy"
$GeneracyDir = $PSScriptRoot
$ConfigFile = Join-Path $GeneracyDir "config.yaml"

# -- Helpers ------------------------------------------------------------------

function Write-Info  { Write-Host "==> $args" -ForegroundColor Blue }
function Write-Ok    { Write-Host "  + $args" -ForegroundColor Green }
function Write-Warn  { Write-Host "  ! $args" -ForegroundColor Yellow }
function Write-Err   { Write-Host "  x $args" -ForegroundColor Red }

function Parse-Repo {
    param([string]$RepoInput)
    $RepoInput = $RepoInput -replace '^https?://github\.com/', '' -replace '^github\.com/', '' -replace '\.git$', '' -replace '/$', ''
    return $RepoInput
}

# -- Step 0: Resolve which cluster layout is in play --------------------------
#
# setup.ps1 configures the *fork/clone* layout, where cluster-base's own compose
# (.devcontainer\generacy\docker-compose.yml) runs the cluster and reads .env
# from that same directory.
#
# Clusters provisioned by the `generacy` CLI or by generacy-cloud are shaped
# differently: their governing compose lives elsewhere (.generacy\docker-
# compose.yml, or a separate host cluster directory) and never loads
# .devcontainer\generacy\.env. Writing that file there reports success while
# changing nothing, and re-mints a fresh smee channel on every run because the
# "already configured" probe reads a file no container loads. Detect that and
# refuse instead of writing a confident no-op. See cluster-base#81.

function Test-CliOrCloudProvisioned {
    if (Test-Path (Join-Path $GeneracyDir "cluster-base.json")) { return $true }
    $envPath = Join-Path $DevcontainerDir ".env"
    if (Test-Path $envPath) {
        $head = (Get-Content -Path $envPath -TotalCount 5 -ErrorAction SilentlyContinue) -join "`n"
        if ($head -match 'Generated by Generacy') { return $true }
    }
    if (Test-Path $ConfigFile) {
        if ((Get-Content -Path $ConfigFile -Raw -ErrorAction SilentlyContinue) -match 'generacy#247') { return $true }
    }
    return $false
}

$ClusterLayout = "unknown"
$EnvFile = ""
if (Test-Path (Join-Path $GeneracyDir "docker-compose.yml")) {
    # Only the generacy CLI scaffolds a compose into .generacy\.
    $ClusterLayout = "cli"
    $EnvFile = Join-Path $GeneracyDir ".env"
} elseif (Test-Path (Join-Path $DevcontainerDir "docker-compose.yml")) {
    if (Test-CliOrCloudProvisioned) {
        # Compose present but the repo carries CLI/cloud provenance - it is a
        # decoy merged from cluster-base; the real cluster runs elsewhere.
        $ClusterLayout = "cloud"
    } else {
        $ClusterLayout = "fork"
        $EnvFile = Join-Path $DevcontainerDir ".env"
    }
}

if ($ClusterLayout -ne "fork") {
    Write-Err "This doesn't look like a fork/clone of cluster-base - refusing to write a no-op."
    Write-Host ""
    switch ($ClusterLayout) {
        "cli" {
            Write-Host "  This cluster is governed by .generacy\docker-compose.yml, which reads"
            Write-Host "  .generacy\.env - not .devcontainer\generacy\.env. That file is owned by"
            Write-Host "  the 'generacy' CLI and carries identity values this script must not"
            Write-Host "  overwrite."
            Write-Host ""
            Write-Host "  To set the smee webhook channel, edit SMEE_CHANNEL_URL in:"
            Write-Host "    $EnvFile"
            Write-Host "  (leave the identity block above it untouched) and restart the cluster."
        }
        "cloud" {
            Write-Host "  This repo was provisioned by generacy-cloud. Its"
            Write-Host "  .devcontainer\generacy\.env is a decoy that no container loads - the"
            Write-Host "  real cluster runs its compose from a separate cluster directory."
            Write-Host ""
            Write-Host "  Configure this cluster through the 'generacy' CLI or your generacy-cloud"
            Write-Host "  project settings instead."
        }
        default {
            Write-Host "  No docker-compose.yml was found governing this cluster (looked in"
            Write-Host "  .generacy\ and .devcontainer\generacy\). If this is a fork, run the"
            Write-Host "  script from the repo root; otherwise configure the cluster through the"
            Write-Host "  tool that provisioned it."
        }
    }
    Write-Host ""
    Write-Host "  Webhook forwarding is moving to cluster-local auto-provisioning"
    Write-Host "  (generacy-ai/generacy#952), which removes the need to run this script for"
    Write-Host "  smee on CLI/cloud clusters."
    Write-Host ""
    exit 1
}

Write-Ok "Cluster layout: fork/clone - configuring $EnvFile"

# -- Step 1: Load or create .generacy/config.yaml ----------------------------

Write-Info "Checking for existing config..."

if (Test-Path $ConfigFile) {
    Write-Info "Found existing .generacy/config.yaml"

    $configContent = Get-Content -Path $ConfigFile -Raw
    $primaryMatch = [regex]::Match($configContent, 'primary:\s*[''"]?([^\s''"]+)[''"]?')
    if ($primaryMatch.Success) {
        $primaryRepoRaw = $primaryMatch.Groups[1].Value
    } else {
        Write-Err "Could not parse primary repo from config.yaml"
        exit 1
    }

    $ownerRepo = Parse-Repo $primaryRepoRaw
    $parts = $ownerRepo -split '/'
    $Owner = $parts[0]
    $RepoName = $parts[1]
    $RepoUrl = "https://github.com/$ownerRepo.git"
    $ProjectName = ($RepoName.ToLower() -replace '[^a-z0-9-]', '-')

    Write-Ok "Primary repo: $ownerRepo"
    Write-Ok "Project name: $ProjectName"

    $configExists = $true
} else {
    $configExists = $false
    Write-Info "No config.yaml found - will create one"

    if (-not $RepoUrl) {
        try { $RepoUrl = git remote get-url origin 2>$null } catch {}
    }
    if (-not $RepoUrl) {
        $RepoUrl = Read-Host "  ? Repository URL (e.g., https://github.com/your-org/your-repo.git)"
    }
    if (-not $RepoUrl) {
        Write-Err "Repository URL is required"
        exit 1
    }

    $ownerRepo = Parse-Repo $RepoUrl
    $parts = $ownerRepo -split '/'
    $Owner = $parts[0]
    $RepoName = $parts[1]
    $ProjectName = ($RepoName.ToLower() -replace '[^a-z0-9-]', '-')

    Write-Ok "Repository: $RepoUrl"
    Write-Ok "Owner: $Owner"
    Write-Ok "Project name: $ProjectName"
    Write-Ok "Repo name: $RepoName"
}

# -- Step 2: Branch -----------------------------------------------------------

if ($configExists) {
    $branchMatch = [regex]::Match($configContent, 'baseBranch:\s*[''"]?([^\s''"]+)[''"]?')
    if ($branchMatch.Success) {
        $RepoBranch = $branchMatch.Groups[1].Value
    } else {
        $RepoBranch = "main"
    }
    Write-Ok "Branch (from config): $RepoBranch"
} else {
    $RepoBranch = try { git symbolic-ref --short HEAD 2>$null } catch { "main" }
    if (-not $RepoBranch) { $RepoBranch = "main" }
    $input = Read-Host "  ? Default branch [$RepoBranch]"
    if ($input) { $RepoBranch = $input }
    Write-Ok "Branch: $RepoBranch"
}

# -- Step 3: Worker count ----------------------------------------------------

$WorkerCount = "3"
$input = Read-Host "  ? Number of workers [$WorkerCount]"
if ($input) { $WorkerCount = $input }
Write-Ok "Workers: $WorkerCount"

# -- Step 4: Create smee.io channel ------------------------------------------

Write-Info "Setting up webhook forwarding..."

$SmeeChannelUrl = ""

# Check the env file the compose actually reads (resolved in Step 0) for a smee
# URL. Reading the right file is what stops a re-run from minting a fresh smee
# channel every time. See cluster-base#81.
if (Test-Path $EnvFile) {
    $existingSmee = (Get-Content $EnvFile | Where-Object { $_ -match '^SMEE_CHANNEL_URL=' }) -replace '^SMEE_CHANNEL_URL=', ''
    if ($existingSmee) { $SmeeChannelUrl = $existingSmee }
}

if ($SmeeChannelUrl) {
    Write-Ok "Smee channel (from existing .env): $SmeeChannelUrl"
} else {
    $createSmee = Read-Host "  ? Create a new smee.io channel? [Y/n]"
    if ($createSmee -ne "n" -and $createSmee -ne "N") {
        try {
            $response = Invoke-WebRequest -Uri "https://smee.io/new" -MaximumRedirection 0 -ErrorAction SilentlyContinue
        } catch {
            if ($_.Exception.Response.Headers.Location) {
                $SmeeChannelUrl = $_.Exception.Response.Headers.Location.ToString()
            }
        }
        if ($SmeeChannelUrl) {
            Write-Ok "Smee channel: $SmeeChannelUrl"
        } else {
            Write-Warn "Could not create smee.io channel automatically"
        }
    }

    if (-not $SmeeChannelUrl) {
        $SmeeChannelUrl = Read-Host "  ? Smee.io channel URL (create one at https://smee.io/new, or press Enter to skip)"
        if ($SmeeChannelUrl) {
            Write-Ok "Smee channel: $SmeeChannelUrl"
        } else {
            Write-Warn "Skipping smee.io - you can add SMEE_CHANNEL_URL to .env later"
        }
    }
}

# -- Step 5: Generate .generacy/config.yaml (if not present) -----------------

if (-not $configExists) {
    Write-Info "Creating .generacy/config.yaml..."
    if (-not (Test-Path $GeneracyDir)) { New-Item -ItemType Directory -Path $GeneracyDir -Force | Out-Null }
    $configYaml = @"
# Generacy project configuration
# Docs: https://github.com/generacy-ai/cluster-base

project:
  name: "$ProjectName"

repos:
  primary: "$Owner/$RepoName"
  dev:
    # Add repos for active development (owner/repo format):
    # - $Owner/another-repo
  clone:
    # Add repos to clone as read-only reference:
    # - $Owner/docs

defaults:
  baseBranch: $RepoBranch
"@
    Set-Content -Path $ConfigFile -Value $configYaml
    Write-Ok "Created $ConfigFile"
}

# -- Step 6: Generate .env (Docker Compose variables) -------------------------

Write-Info "Generating .devcontainer/generacy/.env..."

$writeEnv = $true
if (Test-Path $EnvFile) {
    $overwrite = Read-Host "  ? .env already exists. Overwrite? [y/N]"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Warn "Keeping existing .env"
        $writeEnv = $false
    }
}

if ($writeEnv) {
    $timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    $envContent = @"
# Docker Compose configuration
# Generated by setup.ps1 -- $timestamp
#
# These variables are used by docker-compose.yml for container setup.
# Project config (repos, monitoring, webhooks) lives in .generacy/config.yaml.

PROJECT_NAME=$ProjectName
REPO_URL=https://github.com/$Owner/$RepoName.git
REPO_NAME=$RepoName
REPO_BRANCH=$RepoBranch
WORKER_COUNT=$WorkerCount
ORCHESTRATOR_PORT=3100
GENERACY_CHANNEL=preview
SMEE_CHANNEL_URL=$SmeeChannelUrl
LABEL_MONITOR_ENABLED=true
WEBHOOK_SETUP_ENABLED=true
"@
    Set-Content -Path $EnvFile -Value $envContent -NoNewline
    Write-Ok "Created $EnvFile"
}

# -- Step 7: Generate .env.local (secrets) ------------------------------------

Write-Info "Setting up credentials..."

$EnvLocalFile = Join-Path $DevcontainerDir ".env.local"
$writeLocal = $true

if (Test-Path $EnvLocalFile) {
    $overwrite = Read-Host "  ? .env.local already exists. Overwrite? [y/N]"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Warn "Keeping existing .env.local"
        $writeLocal = $false
    }
}

if ($writeLocal) {
    Write-Host ""
    Write-Info "GitHub fine-grained access token"
    Write-Host "  Create one at: https://github.com/settings/tokens?type=beta"
    Write-Host "  Required permissions: Contents (rw), Issues (rw), Pull requests (rw)"
    Write-Host ""

    $ghTokenSecure = Read-Host "  ? GitHub token" -AsSecureString
    $ghToken = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($ghTokenSecure))

    $ghUsername = Read-Host "  ? GitHub username"
    $ghEmail = Read-Host "  ? GitHub email"

    Write-Host ""
    Write-Info "Claude API key"
    Write-Host "  Get one at: https://console.anthropic.com/settings/keys"
    Write-Host ""

    $claudeKeySecure = Read-Host "  ? Claude API key" -AsSecureString
    $claudeKey = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($claudeKeySecure))

    Write-Host ""
    Write-Host "  Generacy API key" -ForegroundColor Cyan
    Write-Host "    Create one at: https://staging.generacy.ai/settings#api-keys"
    Write-Host "    Required permissions: all access levels"
    Write-Host ""
    $generacyKeySecure = Read-Host "  ? Generacy API key (input hidden)" -AsSecureString
    $generacyKey = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($generacyKeySecure))

    $envLocalContent = @"
# Generated by setup.ps1 -- DO NOT COMMIT
GH_TOKEN=$ghToken
GH_USERNAME=$ghUsername
GH_EMAIL=$ghEmail
CLAUDE_API_KEY=$claudeKey
GENERACY_API_KEY=$generacyKey
"@
    Set-Content -Path $EnvLocalFile -Value $envLocalContent -NoNewline
    Write-Ok "Created $EnvLocalFile"
}

# -- Step 8: Update devcontainer.json ----------------------------------------

Write-Info "Updating devcontainer.json..."

$DevcontainerJson = Join-Path $DevcontainerDir "devcontainer.json"

if (Test-Path $DevcontainerJson) {
    $content = Get-Content -Path $DevcontainerJson -Raw
    $content = $content -replace '"name": "generacy-cluster"', "`"name`": `"$ProjectName`""
    $content = $content -replace '"workspaceFolder": "/workspaces/project"', "`"workspaceFolder`": `"/workspaces/$RepoName`""
    Set-Content -Path $DevcontainerJson -Value $content -NoNewline
    Write-Ok "Updated devcontainer.json (name: $ProjectName, workspaceFolder: /workspaces/$RepoName)"
} else {
    Write-Warn "devcontainer.json not found at $DevcontainerJson"
}

# -- Step 9: Ensure ~/.claude.json exists ------------------------------------

Write-Info "Checking Claude config..."

$ClaudeJson = Join-Path $env:USERPROFILE ".claude.json"

if (-not (Test-Path $ClaudeJson)) {
    Set-Content -Path $ClaudeJson -Value "{}"
    Write-Ok "Created $ClaudeJson (required for Docker volume mount)"
} else {
    Write-Ok "$ClaudeJson already exists"
}

# -- Done ---------------------------------------------------------------------

Write-Host ""
Write-Info "Setup complete!"
Write-Host ""
Write-Host "  Generated files:"
Write-Host "    .generacy/config.yaml                - project configuration (commit this)"
Write-Host "    .devcontainer/generacy/.env          - Docker Compose settings (commit this)"
Write-Host "    .devcontainer/generacy/.env.local    - secrets (gitignored, never commit)"
Write-Host "    .devcontainer/generacy/devcontainer.json - updated with project values"
Write-Host ""
if ($SmeeChannelUrl) {
    Write-Host "  Webhook forwarding:"
    Write-Host "    Add this URL as a webhook in your GitHub repo settings:"
    Write-Host "    $SmeeChannelUrl"
    Write-Host ""
}

# -- Step 10: Offer to commit and push ----------------------------------------

$doCommit = Read-Host "  ? Would you like to commit and push the configuration changes? [y/N]"

if ($doCommit -eq "y" -or $doCommit -eq "Y") {
    Write-Info "Committing configuration changes..."

    Push-Location $ProjectDir

    # Stage only safe files (never .env.local)
    $safeFiles = @(
        ".generacy/config.yaml",
        ".devcontainer/generacy/.env",
        ".devcontainer/generacy/devcontainer.json",
        ".devcontainer/generacy/.gitignore"
    )

    $stagedCount = 0
    foreach ($f in $safeFiles) {
        if (Test-Path $f) {
            git add $f
            Write-Ok "Staged $f"
            $stagedCount++
        }
    }

    if ($stagedCount -eq 0) {
        Write-Warn "No files to commit"
    } else {
        git commit -m "chore: configure generacy cluster for $ProjectName"
        Write-Ok "Committed configuration changes"

        $doPush = Read-Host "  ? Push to origin/$RepoBranch? [y/N]"
        if ($doPush -eq "y" -or $doPush -eq "Y") {
            $currentBranch = git symbolic-ref --short HEAD
            git push origin $currentBranch
            Write-Ok "Pushed to origin"
        } else {
            Write-Info "Skipping push - you can push later with: git push"
        }
    }

    Pop-Location
}

# -- Step 11: Offer to start the cluster ---------------------------------------

Write-Host ""
$doStart = Read-Host "  ? Would you like to start the cluster now? [y/N]"

if ($doStart -eq "y" -or $doStart -eq "Y") {
    Write-Info "Starting cluster..."
    Push-Location $DevcontainerDir
    docker compose up -d
    Pop-Location
    Write-Ok "Cluster started!"
    Write-Host ""
    Write-Host "  You can also open this project in VS Code and select 'Reopen in Container'."
} else {
    Write-Host ""
    Write-Host "  Next steps:"
    Write-Host "    1. Open this project in VS Code"
    Write-Host "    2. VS Code will prompt: 'Reopen in Container' -- select 'generacy'"
    Write-Host "    3. Or run manually: cd .devcontainer/generacy; docker compose up -d"
}
Write-Host ""
